version: '2'
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  #################################################################

  chicken_dinner_bot:
    container_name: chicken_dinner_bot
    build:
      context: .
      dockerfile: Dockerfile-chicken_dinner_bot
    env_file:
      - "./src/chicken-dinner-bot/.env"
    links:
      - redis

  #################################################################

  # pubgtrn_mock_api:
  #   container_name: pubgtrn_mock_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-mock_api
  #   ports:
  #     - "3003:3000"
  #   volumes:
  #     - "./api.md:/usr/src/app/api.md"